/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter2;

public class Calculator {
    
    public int add(int number1, int number2) {
        return number1 + number2;
    }    

    public int addNonNegative(int number1, int number2) {
        if (number1 < 0 || number2 < 0) {
            System.out.println("Negative number");
        }
        return number1 + number2;
    }
    
    /**
     * Purposedly broken substract to demonstrate statement issue
     */
    public int subtract(int number1, int number2) {
        int subs = 0;
        if (number1 < 0 || number2 < 0) {
                System.out.println("Negative number");
                subs = number1 - number2;
        }
       return subs;
    }
    
    /**
     * Purposedly broken method to demonstrate an edge issue
     */
    public int addMultiple(int[] numbers) {
        int toAdd = 0;
        for(int i = 0; i < numbers.length - 1; i++) {
            System.out.println("numbers[i]");
            toAdd += numbers[i];
        }
        return toAdd;
    }
        
    /* 
    * This method is purposedly confusing and long way of doing an addition
    */
    public int confusingAdd(int number1, int number2) {
        if (number1 == 0){
          return number2;
        }
        if (number2 == 0){
            return number1;
        }
        if (number1 == Integer.MAX_VALUE && number2 > 0) {
            throw new IndexOutOfBoundsException("first number too large");
        }
        if (number2 == Integer.MAX_VALUE && number1 > 0) {
            throw new IndexOutOfBoundsException("second number too large");
        }
        if (number1 == Integer.MIN_VALUE && number2 < 0) {
            throw new IndexOutOfBoundsException("first number too small");
        }
        if (number2 == Integer.MIN_VALUE && number1 < 0) {
            throw new IndexOutOfBoundsException("second number too small");
        }
        if (Integer.MAX_VALUE - number1 - number2 < 0) {
            throw new IndexOutOfBoundsException("the addition cannot fit in an integer");
        }
        /* we could add more conditions, the idea is that, even a simple addition could get very complicated */
        return number1 + number2;
    }

    public static void main(String[] args) {
        System.out.println("Calculator app");
    }
}
